In [1]:
import pandas as pd
import numpy as np
import sklearn as sns

In [2]:
df = pd.read_csv("laptopPrice.csv")

In [3]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [4]:
df.duplicated().sum()

np.int64(21)

In [5]:
df.drop_duplicates(inplace=True)

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.info()

<class 'pandas.DataFrame'>
Index: 802 entries, 0 to 822
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              802 non-null    str
 1   processor_brand    802 non-null    str
 2   processor_name     802 non-null    str
 3   processor_gnrtn    802 non-null    str
 4   ram_gb             802 non-null    str
 5   ram_type           802 non-null    str
 6   ssd                802 non-null    str
 7   hdd                802 non-null    str
 8   os                 802 non-null    str
 9   os_bit             802 non-null    str
 10  graphic_card_gb    802 non-null    str
 11  weight             802 non-null    str
 12  warranty           802 non-null    str
 13  Touchscreen        802 non-null    str
 14  msoffice           802 non-null    str
 15  Price              802 non-null    int64
 16  rating             802 non-null    str
 17  Number of Ratings  802 non-null    int64
 18  Number of Reviews  802 non-null    int64
dtypes: int64(3), str(16)
memory usage: 125.3 KB

In [8]:
df['brand'].unique()

<StringArray>
['ASUS', 'Lenovo', 'acer', 'Avita', 'HP', 'DELL', 'MSI', 'APPLE']
Length: 8, dtype: str

In [9]:
df['processor_brand'].unique()

<StringArray>
['Intel', 'AMD', 'M1']
Length: 3, dtype: str

In [10]:
processor_brand ={
    'Intel':1, 'AMD':2, 'M1':3
}

In [11]:
df['processor_brand']=df['processor_brand'].map(processor_brand)

In [12]:
df['processor_name'].unique()

<StringArray>
[     'Core i3',      'Core i5', 'Celeron Dual',      'Ryzen 5',
      'Core i7',      'Core i9',           'M1', 'Pentium Quad',
      'Ryzen 3',      'Ryzen 7',      'Ryzen 9']
Length: 11, dtype: str

In [13]:
processor_name ={
     'Core i3':1,      'Core i5':2, 'Celeron Dual':3,      'Ryzen 5':4,
      'Core i7':5,      'Core i9':6,           'M1':7, 'Pentium Quad':8,
      'Ryzen 3':9,      'Ryzen 7':10,      'Ryzen 9':11
}

In [14]:
df['processor_name']=df['processor_name'].map(processor_name)

In [15]:
df['processor_gnrtn'].unique()

<StringArray>
['10th', 'Not Available', '11th', '7th', '8th', '9th', '4th', '12th']
Length: 8, dtype: str

In [16]:
processor_gnrtn ={
    '10th':10, 'Not Available':0, '11th':11, '7th':7, '8th':8, '9th':9, '4th':4, '12th':12
}

In [17]:
df['processor_gnrtn']=df['processor_gnrtn'].map(processor_gnrtn)

In [18]:
df['ram_gb'].unique()

<StringArray>
['4 GB', '8 GB', '16 GB', '32 GB']
Length: 4, dtype: str

In [19]:
ram_gb ={
    '4 GB':4, '8 GB':8, '16 GB':16, '32 GB':32
}

In [20]:
df['ram_gb']=df['ram_gb'].map(ram_gb)

In [21]:
df['ram_type'].unique()

<StringArray>
['DDR4', 'LPDDR4', 'LPDDR4X', 'DDR5', 'DDR3', 'LPDDR3']
Length: 6, dtype: str

In [22]:
ram_type ={
    'DDR4':1, 'LPDDR4':2, 'LPDDR4X':3, 'DDR5':4, 'DDR3':5, 'LPDDR3':6
}

In [23]:
df['ram_type']=df['ram_type'].map(ram_type)

In [24]:
df['ssd'].unique()

<StringArray>
['0 GB', '512 GB', '256 GB', '128 GB', '1024 GB', '2048 GB', '3072 GB']
Length: 7, dtype: str

In [25]:
ssd ={
    '0 GB':0, '512 GB':512, '256 GB':256, '128 GB':128, '1024 GB':1024, '2048 GB':2048, '3072 GB':3072
}

In [26]:
df['ssd']=df['ssd'].map(ssd)

In [27]:
df['hdd'].unique()

<StringArray>
['1024 GB', '0 GB', '512 GB', '2048 GB']
Length: 4, dtype: str

In [28]:
hdd ={
    '0 GB':0, '512 GB':512, '256 GB':256, '128 GB':128, '1024 GB':1024, '2048 GB':2048, '3072 GB':3072
}

In [29]:
df['hdd']=df['hdd'].map(hdd)

In [30]:
df['os'].unique()

<StringArray>
['Windows', 'DOS', 'Mac']
Length: 3, dtype: str

In [31]:
os ={
    'Windows':1, 'DOS':2, 'Mac':3
}

In [32]:
df['os']=df['os'].map(os)

In [33]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,1,1,10,4,1,0,1024,1,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,1,1,10,4,1,0,1024,1,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,1,1,10,4,1,0,1024,1,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,1,2,10,8,1,512,0,1,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,1,3,0,4,1,0,512,1,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,2,11,0,4,1,1024,0,1,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,2,11,0,4,1,1024,0,1,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,2,11,0,4,1,1024,0,1,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,2,11,0,4,1,1024,0,1,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,2,4,10,8,1,512,0,2,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [34]:
df['os_bit'].unique()

<StringArray>
['64-bit', '32-bit']
Length: 2, dtype: str

In [35]:
os_bit ={
    '64-bit':64, '32-bit':32
}

In [36]:
df['os_bit']=df['os_bit'].map(os_bit)

In [37]:
df['graphic_card_gb'].unique()

<StringArray>
['0 GB', '2 GB', '4 GB', '6 GB', '8 GB']
Length: 5, dtype: str

In [38]:
graphic_card_gb ={
    '0 GB':0, '2 GB':2, '4 GB':4, '6 GB':6, '8 GB':8
}

In [39]:
df['graphic_card_gb']=df['graphic_card_gb'].map(graphic_card_gb)

In [40]:
df['weight'].unique()

<StringArray>
['Casual', 'ThinNlight', 'Gaming']
Length: 3, dtype: str

In [41]:
weight ={
    'Casual':0, 'ThinNlight':1, 'Gaming':2
}

In [42]:
df['weight']=df['weight'].map(weight)

In [43]:
df['warranty'].unique()

<StringArray>
['No warranty', '1 year', '2 years', '3 years']
Length: 4, dtype: str

In [44]:
warranty ={
    'No warranty':0, '1 year':1, '2 years':2, '3 years':3
}

In [45]:
df['warranty']=df['warranty'].map(warranty)

In [46]:
df['Touchscreen'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [47]:
Touchscreen ={
    'No':0, 'Yes':1
}

In [48]:
df['Touchscreen']=df['Touchscreen'].map(Touchscreen)

In [49]:
df['msoffice'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [50]:
msoffice ={
    'No':0, 'Yes':1
}
df['msoffice']=df['msoffice'].map(msoffice)

In [51]:
df['Price'].unique()

array([ 34649,  38999,  39999,  69990,  26990,  22990,  21990,  58799,
        49999,  59990,  93700,  72990,  17490,  35990,  56490,  65390,
        31999,  32490,  31799,  29890,  23990,  32955,  46200,  34429,
        37990,  33980,  39990,  39490,  53990,  38990,  37890,  41990,
        45990,  42490,  36990,  38940,  42990,  49990,  41490,  38490,
        44990,  36490,  38970,  44900,  44427,  40200,  40990,  71999,
        41998,  39998,  48490,  44376,  43900,  46690,  43990,  48500,
        48990,  23490,  54238,  51990,  43970,  54990,  41250,  60790,
        45650,  45490,  38799,  69267,  51649,  47990,  44890,  50990,
        48900,  41790,  57999,  45930,  55490,  32890,  42190,  43690,
        43800,  34990,  38900,  40890,  39790,  35590,  33990,  43400,
        24990,  40750,  43000,  38000,  49279,  41500,  36999,  42900,
        21490,  41480,  32990,  38680,  40390,  20490,  44490,  41890,
        43590,  44690,  41390,  44290,  48999,  46390,  18990,  17990,
        26470,  27990,  29999,  25990,  16990, 119990,  94190, 106167,
        68090, 139990,  55990, 102551,  46990,  76012,  49490,  86867,
        81998, 136590,  59490,  49800,  61999,  52990,  67990,  57990,
        62300,  61990,  63990,  65990,  71990,  76990,  89990,  71890,
        64990,  55999,  73490,  74490,  58340,  82990,  64190,  70090,
        97990,  66999,  60990,  59999,  79990,  69490,  89390,  74990,
        66490,  89702,  70990,  58990,  57500,  56541,  61290,  84990,
        72500,  87990,  68990,  77990, 105990, 111890,  71090,  53400,
        74500, 114990, 159990, 172090, 147000, 106490, 111999,  70798,
        99500,  62998,  88990, 113590,  73990,  61000,  99990,  70799,
        53690,  53190,  58999,  82000,  89998,  69899,  76300,  72900,
        73519, 126000, 114999, 109999, 129999, 149990,  71290,  79500,
        70980,  94000,  85990,  86990,  91999,  78900, 132790,  65556,
        70190,  79590,  86999,  78000,  73063, 100990,  75990,  84086,
       179990,  84500,  74190, 155411, 125394,  52490,  56990,  58090,
        61597,  81990,  61249,  83990, 291190, 145990,  46790,  44599,
        72964,  48790,  56491,  62490,  60190,  54490,  55790,  69900,
        74590,  77900,  67490,  74999,  68900,  71695,  62317, 207290,
        93190,  94990, 102990, 104000,  90190,  88488, 109990, 239759,
        78990, 121890,  92000, 162990, 135300, 174527, 162299, 109190,
        99999, 104990, 244801,  86000, 162399, 119599, 211753, 110999,
        66990, 134990,  98990, 144690, 194990, 124990, 122410, 154990,
       122990, 224990, 279990, 121990, 116990, 151098, 129990, 149999,
       171990,  93955, 234990, 128500, 120980, 157249, 229900, 131500,
       165990, 167990, 165000,  62990, 136990, 233990,  93990, 116941,
        82500,  98912,  92990, 169990, 192990, 299990, 269990, 265998,
       441990, 109590, 146490, 112990, 132990, 125990, 103990, 101990,
       131990, 128990, 184990, 225990, 243990, 309990,  58100,  30990,
        36000,  30780,  33690,  40590,  34500,  43490,  42090,  37390,
        52632,  32917,  41999,  44390,  49970,  47490,  67500,  62450,
        98020,  49890,  73999,  76190,  74798,  68100,  55090,  91990,
        84208,  53490,  76498,  98920,  52380,  52500,  75999,  80990,
        59900,  54590,  75500,  51890,  57900,  81978,  68500,  80000,
        75100, 106990,  81490,  84988,  90990,  72400, 111990, 109000,
        78988,  73138,  89570,  73400,  84190,  95990, 130990,  77988,
        76000, 111000,  84970,  80490, 135990, 199990, 146990, 141990,
       142990, 130500, 138990, 144990,  57490])

In [52]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,1,1,10,4,1,0,1024,1,64,0,0,0,0,0,34649,2 stars,3,0
1,Lenovo,1,1,10,4,1,0,1024,1,64,0,0,0,0,0,38999,3 stars,65,5
2,Lenovo,1,1,10,4,1,0,1024,1,64,0,0,0,0,0,39999,3 stars,8,1
3,ASUS,1,2,10,8,1,512,0,1,32,2,0,0,0,0,69990,3 stars,0,0
4,ASUS,1,3,0,4,1,0,512,1,64,0,0,0,0,0,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,2,11,0,4,1,1024,0,1,64,0,0,1,0,0,135990,3 stars,0,0
819,ASUS,2,11,0,4,1,1024,0,1,64,0,0,1,0,0,144990,3 stars,0,0
820,ASUS,2,11,0,4,1,1024,0,1,64,4,0,1,0,0,149990,3 stars,0,0
821,ASUS,2,11,0,4,1,1024,0,1,64,4,0,1,0,0,142990,3 stars,0,0
822,Lenovo,2,4,10,8,1,512,0,2,64,0,1,0,0,0,57490,4 stars,18,4

In [53]:
df['rating'].unique()

<StringArray>
['2 stars', '3 stars', '4 stars', '5 stars', '1 star']
Length: 5, dtype: str

In [54]:
rating ={
    '2 stars':2, '3 stars':3, '4 stars':4, '5 stars':5, '1 star':1
}

In [55]:
df['rating']=df['rating'].map(rating)

In [56]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,1,1,10,4,1,0,1024,1,64,0,0,0,0,0,34649,2,3,0
1,Lenovo,1,1,10,4,1,0,1024,1,64,0,0,0,0,0,38999,3,65,5
2,Lenovo,1,1,10,4,1,0,1024,1,64,0,0,0,0,0,39999,3,8,1
3,ASUS,1,2,10,8,1,512,0,1,32,2,0,0,0,0,69990,3,0,0
4,ASUS,1,3,0,4,1,0,512,1,64,0,0,0,0,0,26990,3,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,2,11,0,4,1,1024,0,1,64,0,0,1,0,0,135990,3,0,0
819,ASUS,2,11,0,4,1,1024,0,1,64,0,0,1,0,0,144990,3,0,0
820,ASUS,2,11,0,4,1,1024,0,1,64,4,0,1,0,0,149990,3,0,0
821,ASUS,2,11,0,4,1,1024,0,1,64,4,0,1,0,0,142990,3,0,0
822,Lenovo,2,4,10,8,1,512,0,2,64,0,1,0,0,0,57490,4,18,4

In [57]:
x = df.drop(['Price', 'brand'], axis=1)
y = df['Price']

In [58]:
x.duplicated().sum()

np.int64(48)

In [59]:
#x.drop_duplicates(inplace=True)

In [60]:
y.duplicated().sum()

np.int64(397)

In [61]:
#y.drop_duplicates(inplace=True)

In [62]:
df.info()

<class 'pandas.DataFrame'>
Index: 802 entries, 0 to 822
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              802 non-null    str
 1   processor_brand    802 non-null    int64
 2   processor_name     802 non-null    int64
 3   processor_gnrtn    802 non-null    int64
 4   ram_gb             802 non-null    int64
 5   ram_type           802 non-null    int64
 6   ssd                802 non-null    int64
 7   hdd                802 non-null    int64
 8   os                 802 non-null    int64
 9   os_bit             802 non-null    int64
 10  graphic_card_gb    802 non-null    int64
 11  weight             802 non-null    int64
 12  warranty           802 non-null    int64
 13  Touchscreen        802 non-null    int64
 14  msoffice           802 non-null    int64
 15  Price              802 non-null    int64
 16  rating             802 non-null    int64
 17  Number of Ratings  802 non-null    int64
 18  Number of Reviews  802 non-null    int64
dtypes: int64(18), str(1)
memory usage: 125.3 KB

In [63]:
x

,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,rating,Number of Ratings,Number of Reviews
0,1,1,10,4,1,0,1024,1,64,0,0,0,0,0,2,3,0
1,1,1,10,4,1,0,1024,1,64,0,0,0,0,0,3,65,5
2,1,1,10,4,1,0,1024,1,64,0,0,0,0,0,3,8,1
3,1,2,10,8,1,512,0,1,32,2,0,0,0,0,3,0,0
4,1,3,0,4,1,0,512,1,64,0,0,0,0,0,3,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,2,11,0,4,1,1024,0,1,64,0,0,1,0,0,3,0,0
819,2,11,0,4,1,1024,0,1,64,0,0,1,0,0,3,0,0
820,2,11,0,4,1,1024,0,1,64,4,0,1,0,0,3,0,0
821,2,11,0,4,1,1024,0,1,64,4,0,1,0,0,3,0,0
822,2,4,10,8,1,512,0,2,64,0,1,0,0,0,4,18,4

In [64]:
y

0       34649
1       38999
2       39999
3       69990
4       26990
        ...
818    135990
819    144990
820    149990
821    142990
822     57490
Name: Price, Length: 802, dtype: int64

In [65]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [66]:
x_train, y_train, x_test, y_test = x_train, y_train, x_test, y_test.drop_duplicates()

In [67]:
x_test

,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,rating,Number of Ratings,Number of Reviews
196,1,2,0,8,4,0,512,1,32,4,0,0,0,0,4,10966,1185
299,1,2,11,8,3,512,0,1,32,0,0,1,0,1,4,76,14
171,1,1,10,8,1,256,1024,1,64,0,1,1,0,1,5,7,5
537,1,5,10,16,1,1024,0,1,64,6,0,1,0,1,4,17,4
551,1,5,11,16,1,1024,0,1,64,8,0,2,0,0,4,14,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368,1,2,11,8,3,512,0,1,64,0,0,1,1,0,3,0,0
361,1,2,10,8,1,512,0,1,64,0,0,1,1,0,5,2,1
446,1,2,11,8,1,256,1024,1,64,0,0,1,0,0,4,47,0
767,2,10,0,4,1,512,0,1,64,4,0,1,0,0,3,0,0
529,1,5,11,16,1,512,0,1,32,0,0,0,0,0,3,0,0

In [68]:
x_train

,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,rating,Number of Ratings,Number of Reviews
442,1,2,11,8,1,256,1024,1,32,0,0,1,0,1,4,1188,127
598,1,5,10,16,3,0,512,2,32,6,0,0,0,0,3,2,1
452,1,2,11,8,1,256,1024,1,64,2,0,1,0,1,4,33,4
696,2,4,0,8,1,512,0,1,64,0,1,1,0,1,3,0,0
339,1,2,11,8,3,512,0,1,64,0,0,1,1,0,4,35,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,1,1,10,4,1,256,0,1,32,0,0,0,0,0,3,3,0
108,1,1,11,8,1,512,0,1,64,0,0,1,1,0,4,10,1
275,1,2,10,8,1,512,0,1,64,2,0,1,0,1,3,0,0
445,1,2,11,8,1,256,1024,1,64,0,0,1,0,0,3,0,0
104,1,1,11,8,1,512,0,1,64,0,0,1,0,1,4,2058,305

In [69]:
y_test

196     50990
299     72990
171     41490
537    144690
551    129990
        ...
258     47990
588    139990
361    126000
767    106990
529    110999
Name: Price, Length: 115, dtype: int64

In [70]:
y_train

442     50990
598    146490
452     60190
696     59490
339     99990
        ...
73      41990
108     60790
275     57500
445     52990
104     44990
Name: Price, Length: 641, dtype: int64

In [71]:
#from sklearn.linear_model import LinearRegression
#lr = LinearRegression()

In [73]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,1,1,10,4,1,0,1024,1,64,0,0,0,0,0,34649,2,3,0
1,Lenovo,1,1,10,4,1,0,1024,1,64,0,0,0,0,0,38999,3,65,5
2,Lenovo,1,1,10,4,1,0,1024,1,64,0,0,0,0,0,39999,3,8,1
3,ASUS,1,2,10,8,1,512,0,1,32,2,0,0,0,0,69990,3,0,0
4,ASUS,1,3,0,4,1,0,512,1,64,0,0,0,0,0,26990,3,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,2,11,0,4,1,1024,0,1,64,0,0,1,0,0,135990,3,0,0
819,ASUS,2,11,0,4,1,1024,0,1,64,0,0,1,0,0,144990,3,0,0
820,ASUS,2,11,0,4,1,1024,0,1,64,4,0,1,0,0,149990,3,0,0
821,ASUS,2,11,0,4,1,1024,0,1,64,4,0,1,0,0,142990,3,0,0
822,Lenovo,2,4,10,8,1,512,0,2,64,0,1,0,0,0,57490,4,18,4

In [74]:
df.duplicated().sum()

np.int64(0)

In [77]:
from sklearn.svm import SVR
sv = SVR()

In [ ]:
sv.fit(x_train, y_train)

SVR()

In [ ]:
pred =sv.predict(x_test)
pred

array([64028.7919338 , 64089.50255335, 63996.70923421, 64119.39478548,
       64119.44311433, 64119.58053168, 64029.05616895, 64091.44354151,
       64089.30750509, 64055.6243796 , 64068.49272706, 63979.25185903,
       64091.54090069, 64119.63566041, 64090.46189989, 64013.10950745,
       64091.47009768, 64090.4972203 , 64091.44364688, 64119.60704098,
       63979.12469812, 64068.5215641 , 64091.19168443, 64066.46735922,
       64018.02722537, 64068.527047  , 64081.27401076, 64119.6515303 ,
       64067.69154945, 64068.52155596, 63996.19697743, 64090.41297056,
       63989.67021054, 64091.53306879, 64091.41787153, 64067.5846179 ,
       64086.89117286, 64091.30955551, 64065.84660834, 64091.10747064,
       64047.27127282, 64070.68522923, 64090.43933548, 63983.89140293,
       64090.44248239, 64068.43371696, 64119.45340769, 64091.52614274,
       64105.64128543, 63996.88239793, 64091.54269732, 64013.29797804,
       64013.29577283, 64091.4483115 , 64085.12913513, 64119.64687758,
       64114.05133397, 64057.49880264, 64091.53400273, 64119.65194505,
       64012.90284105, 64013.29400181, 64023.59907299, 64023.4318221 ,
       64091.16319292, 64089.61856859, 64119.34830622, 64021.05631785,
       64016.23066854, 63983.36833801, 64119.59170912, 64113.92468449,
       64012.69752509, 64119.63566041, 64067.70102397, 64058.82009705,
       64090.52198329, 64091.5399563 , 64053.68290177, 64090.37736667,
       64068.52775001, 63983.77168737, 63992.05603858, 64068.49272706,
       64067.41146054, 63996.4833411 , 64091.50152352, 64091.41111542,
       64090.65879002, 64119.43296395, 64091.20617105, 64091.53312022,
       64091.53336192, 64087.23357035, 64091.52593779, 64091.29476184,
       64117.83563059, 64091.54090069, 64068.52128522, 64088.27075461,
       64023.00418285, 64068.49805713, 64091.44945216, 64079.17094657,
       64091.46699332, 64087.28445166, 64091.14312298, 63997.68180452,
       64068.46625908, 64090.7147095 , 64090.8009048 , 64119.63585351,
       64084.83422324, 64087.46973336, 63983.67233144, 63996.69839638,
       64038.14854311, 64006.59407389, 64054.63810324, 64091.53219433,
       64119.65030159, 64091.20068293, 64080.45115486, 63996.70945084,
       64091.53251689, 64091.5262187 , 64012.63603785, 64091.10540078,
       64119.64976333, 64068.19231854, 64031.17475259, 64091.09691534,
       64090.94427307, 64119.6385753 , 64068.52706719, 63996.74149951,
       64119.5821204 , 64090.82896222, 64091.52587894, 63996.74925648,
       64117.30527437, 63982.93907636, 64023.18535187, 63996.59614725,
       64090.79439882, 64119.60749564, 63984.18093742, 63997.1469034 ,
       64083.02914627, 64084.78226241, 64089.77647298, 64119.42944203,
       64014.96085849, 63983.99176075, 64091.28384181, 64119.65217404,
       64091.53336192, 64091.48721295, 63995.89327795, 64091.52811856,
       64091.50152352])

In [ ]:
pred[0:100]

array([64028.7919338 , 64089.50255335, 63996.70923421, 64119.39478548,
       64119.44311433, 64119.58053168, 64029.05616895, 64091.44354151,
       64089.30750509, 64055.6243796 , 64068.49272706, 63979.25185903,
       64091.54090069, 64119.63566041, 64090.46189989, 64013.10950745,
       64091.47009768, 64090.4972203 , 64091.44364688, 64119.60704098,
       63979.12469812, 64068.5215641 , 64091.19168443, 64066.46735922,
       64018.02722537, 64068.527047  , 64081.27401076, 64119.6515303 ,
       64067.69154945, 64068.52155596, 63996.19697743, 64090.41297056,
       63989.67021054, 64091.53306879, 64091.41787153, 64067.5846179 ,
       64086.89117286, 64091.30955551, 64065.84660834, 64091.10747064,
       64047.27127282, 64070.68522923, 64090.43933548, 63983.89140293,
       64090.44248239, 64068.43371696, 64119.45340769, 64091.52614274,
       64105.64128543, 63996.88239793, 64091.54269732, 64013.29797804,
       64013.29577283, 64091.4483115 , 64085.12913513, 64119.64687758,
       64114.05133397, 64057.49880264, 64091.53400273, 64119.65194505,
       64012.90284105, 64013.29400181, 64023.59907299, 64023.4318221 ,
       64091.16319292, 64089.61856859, 64119.34830622, 64021.05631785,
       64016.23066854, 63983.36833801, 64119.59170912, 64113.92468449,
       64012.69752509, 64119.63566041, 64067.70102397, 64058.82009705,
       64090.52198329, 64091.5399563 , 64053.68290177, 64090.37736667,
       64068.52775001, 63983.77168737, 63992.05603858, 64068.49272706,
       64067.41146054, 63996.4833411 , 64091.50152352, 64091.41111542,
       64090.65879002, 64119.43296395, 64091.20617105, 64091.53312022,
       64091.53336192, 64087.23357035, 64091.52593779, 64091.29476184,
       64117.83563059, 64091.54090069, 64068.52128522, 64088.27075461])

In [ ]:
sv.score(x_train, y_train)

-0.0649275866046346

In [ ]:
lr

LinearRegression()

In [ ]:
print(x_train.shape)
print(y_train.shape)

(641, 17)
(641,)

In [ ]:
y_train =y_train.values.ravel()

In [ ]:
import imblearn
from imblearn.over_sampling import SMOTE

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

#Apply SMOTE to the training data
sm = SMOTE(random_state=42)

In [ ]:
pred =sv.predict(x_test)
pred

array([64028.7919338 , 64089.50255335, 63996.70923421, 64119.39478548,
       64119.44311433, 64119.58053168, 64029.05616895, 64091.44354151,
       64089.30750509, 64055.6243796 , 64068.49272706, 63979.25185903,
       64091.54090069, 64119.63566041, 64090.46189989, 64013.10950745,
       64091.47009768, 64090.4972203 , 64091.44364688, 64119.60704098,
       63979.12469812, 64068.5215641 , 64091.19168443, 64066.46735922,
       64018.02722537, 64068.527047  , 64081.27401076, 64119.6515303 ,
       64067.69154945, 64068.52155596, 63996.19697743, 64090.41297056,
       63989.67021054, 64091.53306879, 64091.41787153, 64067.5846179 ,
       64086.89117286, 64091.30955551, 64065.84660834, 64091.10747064,
       64047.27127282, 64070.68522923, 64090.43933548, 63983.89140293,
       64090.44248239, 64068.43371696, 64119.45340769, 64091.52614274,
       64105.64128543, 63996.88239793, 64091.54269732, 64013.29797804,
       64013.29577283, 64091.4483115 , 64085.12913513, 64119.64687758,
       64114.05133397, 64057.49880264, 64091.53400273, 64119.65194505,
       64012.90284105, 64013.29400181, 64023.59907299, 64023.4318221 ,
       64091.16319292, 64089.61856859, 64119.34830622, 64021.05631785,
       64016.23066854, 63983.36833801, 64119.59170912, 64113.92468449,
       64012.69752509, 64119.63566041, 64067.70102397, 64058.82009705,
       64090.52198329, 64091.5399563 , 64053.68290177, 64090.37736667,
       64068.52775001, 63983.77168737, 63992.05603858, 64068.49272706,
       64067.41146054, 63996.4833411 , 64091.50152352, 64091.41111542,
       64090.65879002, 64119.43296395, 64091.20617105, 64091.53312022,
       64091.53336192, 64087.23357035, 64091.52593779, 64091.29476184,
       64117.83563059, 64091.54090069, 64068.52128522, 64088.27075461,
       64023.00418285, 64068.49805713, 64091.44945216, 64079.17094657,
       64091.46699332, 64087.28445166, 64091.14312298, 63997.68180452,
       64068.46625908, 64090.7147095 , 64090.8009048 , 64119.63585351,
       64084.83422324, 64087.46973336, 63983.67233144, 63996.69839638,
       64038.14854311, 64006.59407389, 64054.63810324, 64091.53219433,
       64119.65030159, 64091.20068293, 64080.45115486, 63996.70945084,
       64091.53251689, 64091.5262187 , 64012.63603785, 64091.10540078,
       64119.64976333, 64068.19231854, 64031.17475259, 64091.09691534,
       64090.94427307, 64119.6385753 , 64068.52706719, 63996.74149951,
       64119.5821204 , 64090.82896222, 64091.52587894, 63996.74925648,
       64117.30527437, 63982.93907636, 64023.18535187, 63996.59614725,
       64090.79439882, 64119.60749564, 63984.18093742, 63997.1469034 ,
       64083.02914627, 64084.78226241, 64089.77647298, 64119.42944203,
       64014.96085849, 63983.99176075, 64091.28384181, 64119.65217404,
       64091.53336192, 64091.48721295, 63995.89327795, 64091.52811856,
       64091.50152352])

In [ ]:
pred[0:20]

array([64028.7919338 , 64089.50255335, 63996.70923421, 64119.39478548,
       64119.44311433, 64119.58053168, 64029.05616895, 64091.44354151,
       64089.30750509, 64055.6243796 , 64068.49272706, 63979.25185903,
       64091.54090069, 64119.63566041, 64090.46189989, 64013.10950745,
       64091.47009768, 64090.4972203 , 64091.44364688, 64119.60704098])

In [ ]:
y_test[0:20]

196     50990
299     72990
171     41490
537    144690
551    129990
809    142990
610    104990
328     64990
222     51990
415    125394
68      41990
658     32917
239     65990
819    144990
758     57999
433    291190
316    106490
111     45490
280     61290
544    154990
Name: Price, dtype: int64